name: Publish

on:
  release:
    types: [published]

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - id: squid
      run: echo "##[set-output name=version;]$(echo ${{ github.event.release.tag_name }} | cut -d'-' -f1)"

    - name: Build the Docker image
      run: |
        cd ${{ steps.squid.outputs.version }}/
        docker build . -t squid

    - name: Tag image
      run: |
        docker tag squid dmachard/squid:${{ github.event.release.tag_name }}

    - name: Upload to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_LOGIN }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push dmachard/squid:${{ github.event.release.tag_name }}