name: Publish

on:
  release:
    types: [published]

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - id: squid
      run: echo "##[set-output name=version;]$(echo ${{ github.event.release.tag_name }} | cut -d'-' -f1)"

    - id: release
      run: echo "##[set-output name=version;]$(echo ${{ github.event.release.tag_name }} | cut -d'-' -f1,2)"

    - id: latest
      run: echo "##[set-output name=flag;]$(echo ${{ github.event.release.tag_name }} | cut -d'-' -f3)"

    - name: Build the Docker image
      run: |
        cd ${{ steps.squid.outputs.version }}/
        docker build . -t squid

    - name: Tag image
      run: |
        docker tag squid dmachard/squid:${{ steps.release.outputs.version }}
        docker tag squid dmachard/squid:latest

    - name: Tag latest image
      if: steps.latest.outputs.flag == 'latest'
      run:  docker tag squid dmachard/squid:latest

    - name: Upload to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_LOGIN }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push dmachard/squid:${{ steps.release.outputs.version }}

    - name: Upload latest to DockerHub
      if: steps.latest.outputs.flag == 'latest'
      run: |
        docker login -u ${{ secrets.DOCKERHUB_LOGIN }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push dmachard/squid:latest